# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\f.scaduto\Desktop\bonus_tools\main_window.ui'
#
# Created: Thu Feb 26 10:20:35 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(271, 439)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.layout_assembly_data = QtGui.QVBoxLayout()
        self.layout_assembly_data.setObjectName("layout_assembly_data")
        self.groupbox_assembly_data = QtGui.QGroupBox(self.dockWidgetContents)
        self.groupbox_assembly_data.setObjectName("groupbox_assembly_data")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupbox_assembly_data)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_insert_assembly_path_source = QtGui.QLabel(self.groupbox_assembly_data)
        self.label_insert_assembly_path_source.setObjectName("label_insert_assembly_path_source")
        self.verticalLayout_3.addWidget(self.label_insert_assembly_path_source)
        self.textedit_insert_cube_name = QtGui.QPlainTextEdit(self.groupbox_assembly_data)
        self.textedit_insert_cube_name.setObjectName("textedit_insert_cube_name")
        self.verticalLayout_3.addWidget(self.textedit_insert_cube_name)
        self.button_replace_assemblies_datas = QtGui.QPushButton(self.groupbox_assembly_data)
        self.button_replace_assemblies_datas.setObjectName("button_replace_assemblies_datas")
        self.verticalLayout_3.addWidget(self.button_replace_assemblies_datas)
        self.layout_assembly_data.addWidget(self.groupbox_assembly_data)
        self.verticalLayout_2.addLayout(self.layout_assembly_data)
        self.layout_object_to_assembly = QtGui.QVBoxLayout()
        self.layout_object_to_assembly.setObjectName("layout_object_to_assembly")
        self.groupBox_object_to_assembly_replacement = QtGui.QGroupBox(self.dockWidgetContents)
        self.groupBox_object_to_assembly_replacement.setObjectName("groupBox_object_to_assembly_replacement")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_object_to_assembly_replacement)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_inser_assembly_source_name = QtGui.QLabel(self.groupBox_object_to_assembly_replacement)
        self.label_inser_assembly_source_name.setObjectName("label_inser_assembly_source_name")
        self.verticalLayout_5.addWidget(self.label_inser_assembly_source_name)
        self.textedit_insert_assembly_source_name = QtGui.QPlainTextEdit(self.groupBox_object_to_assembly_replacement)
        self.textedit_insert_assembly_source_name.setObjectName("textedit_insert_assembly_source_name")
        self.verticalLayout_5.addWidget(self.textedit_insert_assembly_source_name)
        self.button_replace_selected_object_to_assembly = QtGui.QPushButton(self.groupBox_object_to_assembly_replacement)
        self.button_replace_selected_object_to_assembly.setObjectName("button_replace_selected_object_to_assembly")
        self.verticalLayout_5.addWidget(self.button_replace_selected_object_to_assembly)
        self.layout_object_to_assembly.addWidget(self.groupBox_object_to_assembly_replacement)
        self.verticalLayout_2.addLayout(self.layout_object_to_assembly)
        self.layout_assemblies_converter = QtGui.QVBoxLayout()
        self.layout_assemblies_converter.setObjectName("layout_assemblies_converter")
        self.groupBox_assemblies_converter = QtGui.QGroupBox(self.dockWidgetContents)
        self.groupBox_assemblies_converter.setObjectName("groupBox_assemblies_converter")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_assemblies_converter)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_select_assemblies_to_convert = QtGui.QLabel(self.groupBox_assemblies_converter)
        self.label_select_assemblies_to_convert.setObjectName("label_select_assemblies_to_convert")
        self.verticalLayout_4.addWidget(self.label_select_assemblies_to_convert)
        self.layout_convert_to = QtGui.QHBoxLayout()
        self.layout_convert_to.setObjectName("layout_convert_to")
        self.button_convert_to_gpucache = QtGui.QPushButton(self.groupBox_assemblies_converter)
        self.button_convert_to_gpucache.setObjectName("button_convert_to_gpucache")
        self.layout_convert_to.addWidget(self.button_convert_to_gpucache)
        self.button_convert_to_geometry = QtGui.QPushButton(self.groupBox_assemblies_converter)
        self.button_convert_to_geometry.setObjectName("button_convert_to_geometry")
        self.layout_convert_to.addWidget(self.button_convert_to_geometry)
        self.verticalLayout_4.addLayout(self.layout_convert_to)
        self.layout_assemblies_converter.addWidget(self.groupBox_assemblies_converter)
        self.verticalLayout_2.addLayout(self.layout_assemblies_converter)
        MainWindow.setWidget(self.dockWidgetContents)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "DockWidget", None, QtGui.QApplication.UnicodeUTF8))
        self.groupbox_assembly_data.setTitle(QtGui.QApplication.translate("MainWindow", "Assembly data replacement", None, QtGui.QApplication.UnicodeUTF8))
        self.label_insert_assembly_path_source.setText(QtGui.QApplication.translate("MainWindow", "Insert Asset Cube Name", None, QtGui.QApplication.UnicodeUTF8))
        self.textedit_insert_cube_name.setPlainText(QtGui.QApplication.translate("MainWindow", "\"cube001\"", None, QtGui.QApplication.UnicodeUTF8))
        self.button_replace_assemblies_datas.setText(QtGui.QApplication.translate("MainWindow", "Replace Selected Assemblies Datas", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_object_to_assembly_replacement.setTitle(QtGui.QApplication.translate("MainWindow", "Objects to assembly replacement", None, QtGui.QApplication.UnicodeUTF8))
        self.label_inser_assembly_source_name.setText(QtGui.QApplication.translate("MainWindow", "Insert Assembly Source Name", None, QtGui.QApplication.UnicodeUTF8))
        self.textedit_insert_assembly_source_name.setPlainText(QtGui.QApplication.translate("MainWindow", "\"PR_cube001_MODEL_001\"", None, QtGui.QApplication.UnicodeUTF8))
        self.button_replace_selected_object_to_assembly.setText(QtGui.QApplication.translate("MainWindow", "Replace Selected Object To Assemblies", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_assemblies_converter.setTitle(QtGui.QApplication.translate("MainWindow", "Assemblies Converter", None, QtGui.QApplication.UnicodeUTF8))
        self.label_select_assemblies_to_convert.setText(QtGui.QApplication.translate("MainWindow", "Select Assemblies to convert", None, QtGui.QApplication.UnicodeUTF8))
        self.button_convert_to_gpucache.setText(QtGui.QApplication.translate("MainWindow", "Convert To GPUcache", None, QtGui.QApplication.UnicodeUTF8))
        self.button_convert_to_geometry.setText(QtGui.QApplication.translate("MainWindow", "Convert To Geometry", None, QtGui.QApplication.UnicodeUTF8))

