# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'R:\rd\users\f.scaduto\stella_serie\dev\libs\assemblies\main_window.ui'
#
# Created: Thu Feb 19 16:30:44 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(355, 518)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupbox_assets = QtGui.QGroupBox(self.dockWidgetContents)
        self.groupbox_assets.setObjectName("groupbox_assets")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupbox_assets)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_asset_list = QtGui.QLabel(self.groupbox_assets)
        self.label_asset_list.setObjectName("label_asset_list")
        self.verticalLayout_3.addWidget(self.label_asset_list)
        self.textedit_asset_list = QtGui.QPlainTextEdit(self.groupbox_assets)
        self.textedit_asset_list.setObjectName("textedit_asset_list")
        self.verticalLayout_3.addWidget(self.textedit_asset_list)
        self.layout_asset_options = QtGui.QHBoxLayout()
        self.layout_asset_options.setObjectName("layout_asset_options")
        self.label_asset_types = QtGui.QLabel(self.groupbox_assets)
        self.label_asset_types.setObjectName("label_asset_types")
        self.layout_asset_options.addWidget(self.label_asset_types)
        self.combo_asset_types = QtGui.QComboBox(self.groupbox_assets)
        self.combo_asset_types.setObjectName("combo_asset_types")
        self.combo_asset_types.addItem("")
        self.combo_asset_types.addItem("")
        self.combo_asset_types.addItem("")
        self.combo_asset_types.addItem("")
        self.combo_asset_types.addItem("")
        self.combo_asset_types.addItem("")
        self.combo_asset_types.addItem("")
        self.layout_asset_options.addWidget(self.combo_asset_types)
        self.groupbox_asset_save = QtGui.QGroupBox(self.groupbox_assets)
        self.groupbox_asset_save.setObjectName("groupbox_asset_save")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupbox_asset_save)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radio_asset_save_wip = QtGui.QRadioButton(self.groupbox_asset_save)
        self.radio_asset_save_wip.setChecked(True)
        self.radio_asset_save_wip.setObjectName("radio_asset_save_wip")
        self.horizontalLayout_2.addWidget(self.radio_asset_save_wip)
        self.radio_asset_save_publish = QtGui.QRadioButton(self.groupbox_asset_save)
        self.radio_asset_save_publish.setObjectName("radio_asset_save_publish")
        self.horizontalLayout_2.addWidget(self.radio_asset_save_publish)
        self.layout_asset_options.addWidget(self.groupbox_asset_save)
        self.layout_asset_options.setStretch(1, 10)
        self.verticalLayout_3.addLayout(self.layout_asset_options)
        self.verticalLayout_2.addWidget(self.groupbox_assets)
        self.groupbox_process = QtGui.QGroupBox(self.dockWidgetContents)
        self.groupbox_process.setObjectName("groupbox_process")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupbox_process)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupbox_process_auto = QtGui.QGroupBox(self.groupbox_process)
        self.groupbox_process_auto.setFlat(True)
        self.groupbox_process_auto.setCheckable(True)
        self.groupbox_process_auto.setChecked(False)
        self.groupbox_process_auto.setObjectName("groupbox_process_auto")
        self.gridLayout = QtGui.QGridLayout(self.groupbox_process_auto)
        self.gridLayout.setObjectName("gridLayout")
        self.radio_process_auto_batch = QtGui.QRadioButton(self.groupbox_process_auto)
        self.radio_process_auto_batch.setObjectName("radio_process_auto_batch")
        self.gridLayout.addWidget(self.radio_process_auto_batch, 1, 0, 1, 1)
        self.checkbox_process_auto_modeling_anima = QtGui.QCheckBox(self.groupbox_process_auto)
        self.checkbox_process_auto_modeling_anima.setEnabled(False)
        self.checkbox_process_auto_modeling_anima.setObjectName("checkbox_process_auto_modeling_anima")
        self.gridLayout.addWidget(self.checkbox_process_auto_modeling_anima, 2, 0, 1, 1)
        self.checkbox_process_auto_abc_anima = QtGui.QCheckBox(self.groupbox_process_auto)
        self.checkbox_process_auto_abc_anima.setEnabled(False)
        self.checkbox_process_auto_abc_anima.setObjectName("checkbox_process_auto_abc_anima")
        self.gridLayout.addWidget(self.checkbox_process_auto_abc_anima, 2, 1, 1, 1)
        self.checkbox_process_auto_setuplod0 = QtGui.QCheckBox(self.groupbox_process_auto)
        self.checkbox_process_auto_setuplod0.setEnabled(False)
        self.checkbox_process_auto_setuplod0.setObjectName("checkbox_process_auto_setuplod0")
        self.gridLayout.addWidget(self.checkbox_process_auto_setuplod0, 3, 0, 1, 1)
        self.checkbox_process_auto_setuplod2 = QtGui.QCheckBox(self.groupbox_process_auto)
        self.checkbox_process_auto_setuplod2.setEnabled(False)
        self.checkbox_process_auto_setuplod2.setObjectName("checkbox_process_auto_setuplod2")
        self.gridLayout.addWidget(self.checkbox_process_auto_setuplod2, 3, 1, 1, 1)
        self.checkbox_process_auto_assembly_def = QtGui.QCheckBox(self.groupbox_process_auto)
        self.checkbox_process_auto_assembly_def.setEnabled(False)
        self.checkbox_process_auto_assembly_def.setObjectName("checkbox_process_auto_assembly_def")
        self.gridLayout.addWidget(self.checkbox_process_auto_assembly_def, 4, 0, 1, 1)
        self.checkbox_process_auto_assembly_ref = QtGui.QCheckBox(self.groupbox_process_auto)
        self.checkbox_process_auto_assembly_ref.setEnabled(False)
        self.checkbox_process_auto_assembly_ref.setObjectName("checkbox_process_auto_assembly_ref")
        self.gridLayout.addWidget(self.checkbox_process_auto_assembly_ref, 4, 1, 1, 1)
        self.radio_process_auto_add_tasks = QtGui.QRadioButton(self.groupbox_process_auto)
        self.radio_process_auto_add_tasks.setObjectName("radio_process_auto_add_tasks")
        self.gridLayout.addWidget(self.radio_process_auto_add_tasks, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupbox_process_auto)
        self.groupbox_process_manual = QtGui.QGroupBox(self.groupbox_process)
        self.groupbox_process_manual.setFlat(True)
        self.groupbox_process_manual.setCheckable(True)
        self.groupbox_process_manual.setChecked(False)
        self.groupbox_process_manual.setObjectName("groupbox_process_manual")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupbox_process_manual)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.button_process_manual_setuplod0 = QtGui.QPushButton(self.groupbox_process_manual)
        self.button_process_manual_setuplod0.setObjectName("button_process_manual_setuplod0")
        self.gridLayout_2.addWidget(self.button_process_manual_setuplod0, 0, 0, 1, 1)
        self.button_process_manual_abc_representation = QtGui.QPushButton(self.groupbox_process_manual)
        self.button_process_manual_abc_representation.setObjectName("button_process_manual_abc_representation")
        self.gridLayout_2.addWidget(self.button_process_manual_abc_representation, 0, 1, 1, 1)
        self.button_process_manual_add_tags = QtGui.QPushButton(self.groupbox_process_manual)
        self.button_process_manual_add_tags.setObjectName("button_process_manual_add_tags")
        self.gridLayout_2.addWidget(self.button_process_manual_add_tags, 1, 0, 1, 2)
        self.verticalLayout.addWidget(self.groupbox_process_manual)
        self.verticalLayout_2.addWidget(self.groupbox_process)
        self.button_run = QtGui.QPushButton(self.dockWidgetContents)
        self.button_run.setObjectName("button_run")
        self.verticalLayout_2.addWidget(self.button_run)
        MainWindow.setWidget(self.dockWidgetContents)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "DockWidget", None, QtGui.QApplication.UnicodeUTF8))
        self.groupbox_assets.setTitle(QtGui.QApplication.translate("MainWindow", "Assets", None, QtGui.QApplication.UnicodeUTF8))
        self.label_asset_list.setText(QtGui.QApplication.translate("MainWindow", "Insert Asset or Assets list :", None, QtGui.QApplication.UnicodeUTF8))
        self.textedit_asset_list.setPlainText(QtGui.QApplication.translate("MainWindow", "[\'test001\', \'test002\', \'test_A\', \'test_B\']", None, QtGui.QApplication.UnicodeUTF8))
        self.label_asset_types.setText(QtGui.QApplication.translate("MainWindow", "Assets Types :", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_asset_types.setItemText(0, QtGui.QApplication.translate("MainWindow", "PR_props", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_asset_types.setItemText(1, QtGui.QApplication.translate("MainWindow", "CH_characters", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_asset_types.setItemText(2, QtGui.QApplication.translate("MainWindow", "FX_fxs", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_asset_types.setItemText(3, QtGui.QApplication.translate("MainWindow", "BG_decors", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_asset_types.setItemText(4, QtGui.QApplication.translate("MainWindow", "MT_mattes", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_asset_types.setItemText(5, QtGui.QApplication.translate("MainWindow", "CM_camera", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_asset_types.setItemText(6, QtGui.QApplication.translate("MainWindow", "AM_ambiances", None, QtGui.QApplication.UnicodeUTF8))
        self.groupbox_asset_save.setTitle(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_asset_save_wip.setText(QtGui.QApplication.translate("MainWindow", "Wip", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_asset_save_publish.setText(QtGui.QApplication.translate("MainWindow", "Publish", None, QtGui.QApplication.UnicodeUTF8))
        self.groupbox_process.setTitle(QtGui.QApplication.translate("MainWindow", "Process", None, QtGui.QApplication.UnicodeUTF8))
        self.groupbox_process_auto.setTitle(QtGui.QApplication.translate("MainWindow", "Automatic :", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_process_auto_batch.setText(QtGui.QApplication.translate("MainWindow", "Batch :", None, QtGui.QApplication.UnicodeUTF8))
        self.checkbox_process_auto_modeling_anima.setText(QtGui.QApplication.translate("MainWindow", "Modeling Anima", None, QtGui.QApplication.UnicodeUTF8))
        self.checkbox_process_auto_abc_anima.setText(QtGui.QApplication.translate("MainWindow", "Abc Anima", None, QtGui.QApplication.UnicodeUTF8))
        self.checkbox_process_auto_setuplod0.setText(QtGui.QApplication.translate("MainWindow", "SetupLOD0", None, QtGui.QApplication.UnicodeUTF8))
        self.checkbox_process_auto_setuplod2.setText(QtGui.QApplication.translate("MainWindow", "SetupLOD2", None, QtGui.QApplication.UnicodeUTF8))
        self.checkbox_process_auto_assembly_def.setText(QtGui.QApplication.translate("MainWindow", "AssemblyDef", None, QtGui.QApplication.UnicodeUTF8))
        self.checkbox_process_auto_assembly_ref.setText(QtGui.QApplication.translate("MainWindow", "AssemblyRef", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_process_auto_add_tasks.setText(QtGui.QApplication.translate("MainWindow", "Add cube Tasks", None, QtGui.QApplication.UnicodeUTF8))
        self.groupbox_process_manual.setTitle(QtGui.QApplication.translate("MainWindow", "Manual :", None, QtGui.QApplication.UnicodeUTF8))
        self.button_process_manual_setuplod0.setText(QtGui.QApplication.translate("MainWindow", "Create SetupLOD0", None, QtGui.QApplication.UnicodeUTF8))
        self.button_process_manual_abc_representation.setText(QtGui.QApplication.translate("MainWindow", "Create Abc Representations", None, QtGui.QApplication.UnicodeUTF8))
        self.button_process_manual_add_tags.setText(QtGui.QApplication.translate("MainWindow", "Add tags", None, QtGui.QApplication.UnicodeUTF8))
        self.button_run.setText(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))

