# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\development\Ui\BSM\BSM.ui'
#
# Created: Sun Jan 31 13:23:22 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(553, 414)
        Dialog.setMinimumSize(QtCore.QSize(0, 0))
        Dialog.setMaximumSize(QtCore.QSize(16777215, 414))
        self.gridLayout_3 = QtGui.QGridLayout(Dialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setMinimumSize(QtCore.QSize(230, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(3000, 400))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.bs_node_menu = QtGui.QComboBox(self.groupBox_2)
        self.bs_node_menu.setMinimumSize(QtCore.QSize(140, 35))
        self.bs_node_menu.setEditable(False)
        self.bs_node_menu.setObjectName("bs_node_menu")
        self.gridLayout_4.addWidget(self.bs_node_menu, 0, 0, 1, 1)
        self.bs_targets_list = QtGui.QListWidget(self.groupBox_2)
        self.bs_targets_list.setMinimumSize(QtCore.QSize(200, 0))
        self.bs_targets_list.setMaximumSize(QtCore.QSize(3000, 16777215))
        self.bs_targets_list.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.bs_targets_list.setObjectName("bs_targets_list")
        QtGui.QListWidgetItem(self.bs_targets_list)
        QtGui.QListWidgetItem(self.bs_targets_list)
        QtGui.QListWidgetItem(self.bs_targets_list)
        self.gridLayout_4.addWidget(self.bs_targets_list, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setMaximumSize(QtCore.QSize(300, 400))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout = QtGui.QGridLayout(self.tab_2)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtGui.QGroupBox(self.tab_2)
        self.groupBox.setMinimumSize(QtCore.QSize(275, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(275, 400))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.refresh_button = QtGui.QPushButton(self.groupBox)
        self.refresh_button.setMinimumSize(QtCore.QSize(0, 35))
        self.refresh_button.setObjectName("refresh_button")
        self.gridLayout_2.addWidget(self.refresh_button, 1, 0, 1, 2)
        self.create_bs_button = QtGui.QPushButton(self.groupBox)
        self.create_bs_button.setMinimumSize(QtCore.QSize(0, 35))
        self.create_bs_button.setObjectName("create_bs_button")
        self.gridLayout_2.addWidget(self.create_bs_button, 2, 0, 1, 2)
        self.add_targets_button = QtGui.QPushButton(self.groupBox)
        self.add_targets_button.setMinimumSize(QtCore.QSize(0, 35))
        self.add_targets_button.setObjectName("add_targets_button")
        self.gridLayout_2.addWidget(self.add_targets_button, 3, 0, 1, 2)
        self.extract_targets_button = QtGui.QPushButton(self.groupBox)
        self.extract_targets_button.setMinimumSize(QtCore.QSize(0, 35))
        self.extract_targets_button.setObjectName("extract_targets_button")
        self.gridLayout_2.addWidget(self.extract_targets_button, 4, 0, 1, 2)
        self.delete_bs_button = QtGui.QPushButton(self.groupBox)
        self.delete_bs_button.setMinimumSize(QtCore.QSize(0, 35))
        self.delete_bs_button.setObjectName("delete_bs_button")
        self.gridLayout_2.addWidget(self.delete_bs_button, 5, 0, 1, 2)
        self.remove_targets_button = QtGui.QPushButton(self.groupBox)
        self.remove_targets_button.setMinimumSize(QtCore.QSize(0, 35))
        self.remove_targets_button.setObjectName("remove_targets_button")
        self.gridLayout_2.addWidget(self.remove_targets_button, 6, 0, 1, 2)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 7, 0, 1, 1)
        self.inbetween_value = QtGui.QDoubleSpinBox(self.groupBox)
        self.inbetween_value.setMinimumSize(QtCore.QSize(0, 35))
        self.inbetween_value.setMinimum(-99.99)
        self.inbetween_value.setSingleStep(0.1)
        self.inbetween_value.setProperty("value", 0.5)
        self.inbetween_value.setObjectName("inbetween_value")
        self.gridLayout_2.addWidget(self.inbetween_value, 7, 1, 1, 1)
        self.add_inbetween_button = QtGui.QPushButton(self.groupBox)
        self.add_inbetween_button.setMinimumSize(QtCore.QSize(0, 35))
        self.add_inbetween_button.setObjectName("add_inbetween_button")
        self.gridLayout_2.addWidget(self.add_inbetween_button, 8, 0, 1, 2)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_5 = QtGui.QGridLayout(self.tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox_3 = QtGui.QGroupBox(self.tab)
        self.groupBox_3.setMinimumSize(QtCore.QSize(275, 0))
        self.groupBox_3.setMaximumSize(QtCore.QSize(275, 400))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox_3)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setMinimumSize(QtCore.QSize(125, 35))
        self.label_6.setMaximumSize(QtCore.QSize(125, 16777215))
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_6)
        self.controllers_menu = QtGui.QComboBox(self.groupBox_3)
        self.controllers_menu.setMinimumSize(QtCore.QSize(125, 35))
        self.controllers_menu.setMaximumSize(QtCore.QSize(125, 16777215))
        self.controllers_menu.setObjectName("controllers_menu")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.controllers_menu)
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setMinimumSize(QtCore.QSize(125, 35))
        self.label_7.setMaximumSize(QtCore.QSize(125, 16777215))
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_7)
        self.attributes_menu = QtGui.QComboBox(self.groupBox_3)
        self.attributes_menu.setMinimumSize(QtCore.QSize(125, 35))
        self.attributes_menu.setMaximumSize(QtCore.QSize(125, 16777215))
        self.attributes_menu.setObjectName("attributes_menu")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.attributes_menu)
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setMinimumSize(QtCore.QSize(125, 35))
        self.label_2.setMaximumSize(QtCore.QSize(125, 25))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setMinimumSize(QtCore.QSize(125, 35))
        self.label_3.setMaximumSize(QtCore.QSize(125, 25))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.label_3)
        self.min_value = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.min_value.setMinimumSize(QtCore.QSize(125, 35))
        self.min_value.setMaximumSize(QtCore.QSize(125, 16777215))
        self.min_value.setMinimum(-99.99)
        self.min_value.setSingleStep(0.1)
        self.min_value.setObjectName("min_value")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.min_value)
        self.max_value = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.max_value.setMinimumSize(QtCore.QSize(125, 35))
        self.max_value.setMaximumSize(QtCore.QSize(125, 16777215))
        self.max_value.setMinimum(-99.99)
        self.max_value.setSingleStep(0.1)
        self.max_value.setObjectName("max_value")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.max_value)
        self.negative = QtGui.QCheckBox(self.groupBox_3)
        self.negative.setMinimumSize(QtCore.QSize(125, 35))
        self.negative.setMaximumSize(QtCore.QSize(125, 16777215))
        self.negative.setObjectName("negative")
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.negative)
        self.new_attr_name = QtGui.QLineEdit(self.groupBox_3)
        self.new_attr_name.setMinimumSize(QtCore.QSize(125, 35))
        self.new_attr_name.setMaximumSize(QtCore.QSize(125, 16777215))
        self.new_attr_name.setObjectName("new_attr_name")
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.new_attr_name)
        self.connect_button = QtGui.QPushButton(self.groupBox_3)
        self.connect_button.setMinimumSize(QtCore.QSize(125, 35))
        self.connect_button.setMaximumSize(QtCore.QSize(125, 16777215))
        self.connect_button.setObjectName("connect_button")
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.connect_button)
        self.create_attr_button = QtGui.QPushButton(self.groupBox_3)
        self.create_attr_button.setMinimumSize(QtCore.QSize(125, 35))
        self.create_attr_button.setMaximumSize(QtCore.QSize(125, 16777215))
        self.create_attr_button.setObjectName("create_attr_button")
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.create_attr_button)
        self.disconnect_button = QtGui.QPushButton(self.groupBox_3)
        self.disconnect_button.setMinimumSize(QtCore.QSize(125, 35))
        self.disconnect_button.setMaximumSize(QtCore.QSize(125, 16777215))
        self.disconnect_button.setObjectName("disconnect_button")
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.LabelRole, self.disconnect_button)
        self.delete_attr_button = QtGui.QPushButton(self.groupBox_3)
        self.delete_attr_button.setMinimumSize(QtCore.QSize(125, 35))
        self.delete_attr_button.setMaximumSize(QtCore.QSize(125, 16777215))
        self.delete_attr_button.setObjectName("delete_attr_button")
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.FieldRole, self.delete_attr_button)
        self.export_connections_button = QtGui.QPushButton(self.groupBox_3)
        self.export_connections_button.setMinimumSize(QtCore.QSize(125, 35))
        self.export_connections_button.setMaximumSize(QtCore.QSize(125, 16777215))
        self.export_connections_button.setObjectName("export_connections_button")
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.LabelRole, self.export_connections_button)
        self.import_connections_button = QtGui.QPushButton(self.groupBox_3)
        self.import_connections_button.setMinimumSize(QtCore.QSize(125, 35))
        self.import_connections_button.setMaximumSize(QtCore.QSize(125, 16777215))
        self.import_connections_button.setObjectName("import_connections_button")
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.FieldRole, self.import_connections_button)
        self.reset_all_ctrl = QtGui.QPushButton(self.groupBox_3)
        self.reset_all_ctrl.setMinimumSize(QtCore.QSize(125, 35))
        self.reset_all_ctrl.setMaximumSize(QtCore.QSize(125, 16777215))
        self.reset_all_ctrl.setObjectName("reset_all_ctrl")
        self.formLayout_2.setWidget(8, QtGui.QFormLayout.LabelRole, self.reset_all_ctrl)
        self.gridLayout_5.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 1, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog", "Blendshape targets", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.bs_targets_list.isSortingEnabled()
        self.bs_targets_list.setSortingEnabled(False)
        self.bs_targets_list.item(0).setText(QtGui.QApplication.translate("Dialog", "Nouvel élément", None, QtGui.QApplication.UnicodeUTF8))
        self.bs_targets_list.item(1).setText(QtGui.QApplication.translate("Dialog", "Nouvel élément", None, QtGui.QApplication.UnicodeUTF8))
        self.bs_targets_list.item(2).setText(QtGui.QApplication.translate("Dialog", "Nouvel élément", None, QtGui.QApplication.UnicodeUTF8))
        self.bs_targets_list.setSortingEnabled(__sortingEnabled)
        self.refresh_button.setText(QtGui.QApplication.translate("Dialog", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.create_bs_button.setText(QtGui.QApplication.translate("Dialog", "Create blendshape", None, QtGui.QApplication.UnicodeUTF8))
        self.add_targets_button.setText(QtGui.QApplication.translate("Dialog", "Add target(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.extract_targets_button.setText(QtGui.QApplication.translate("Dialog", "Extract target(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.delete_bs_button.setText(QtGui.QApplication.translate("Dialog", "Delete blendshape node(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.remove_targets_button.setText(QtGui.QApplication.translate("Dialog", "Remove target(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "In-between value", None, QtGui.QApplication.UnicodeUTF8))
        self.add_inbetween_button.setText(QtGui.QApplication.translate("Dialog", "Add in-between", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Dialog", "Blendshapes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Controller", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Attribute", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Min", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Max", None, QtGui.QApplication.UnicodeUTF8))
        self.negative.setText(QtGui.QApplication.translate("Dialog", "Negative", None, QtGui.QApplication.UnicodeUTF8))
        self.new_attr_name.setText(QtGui.QApplication.translate("Dialog", "New Attribute name", None, QtGui.QApplication.UnicodeUTF8))
        self.connect_button.setText(QtGui.QApplication.translate("Dialog", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.create_attr_button.setText(QtGui.QApplication.translate("Dialog", "Create attribute", None, QtGui.QApplication.UnicodeUTF8))
        self.disconnect_button.setText(QtGui.QApplication.translate("Dialog", "Disconnect", None, QtGui.QApplication.UnicodeUTF8))
        self.delete_attr_button.setText(QtGui.QApplication.translate("Dialog", "Delete attribute", None, QtGui.QApplication.UnicodeUTF8))
        self.export_connections_button.setText(QtGui.QApplication.translate("Dialog", "Export connections", None, QtGui.QApplication.UnicodeUTF8))
        self.import_connections_button.setText(QtGui.QApplication.translate("Dialog", "Import connections", None, QtGui.QApplication.UnicodeUTF8))
        self.reset_all_ctrl.setText(QtGui.QApplication.translate("Dialog", "Reset controllers", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Dialog", "Controllers", None, QtGui.QApplication.UnicodeUTF8))

