# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\development\Ui\Asset_Manager\Asset_Manager.ui'
#
# Created: Sun Apr 24 20:43:05 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Asset_Manager_MainWindow(object):
    def setupUi(self, Asset_Manager_MainWindow):
        Asset_Manager_MainWindow.setObjectName("Asset_Manager_MainWindow")
        Asset_Manager_MainWindow.resize(290, 503)
        self.centralwidget = QtGui.QWidget(Asset_Manager_MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(9, 9, 272, 465))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.version_listWidget = QtGui.QListWidget(self.groupBox)
        self.version_listWidget.setMinimumSize(QtCore.QSize(0, 150))
        self.version_listWidget.setObjectName("version_listWidget")
        self.gridLayout.addWidget(self.version_listWidget, 6, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.save_pushButton = QtGui.QPushButton(self.groupBox)
        self.save_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        self.save_pushButton.setObjectName("save_pushButton")
        self.horizontalLayout_5.addWidget(self.save_pushButton)
        self.wip_pushButton = QtGui.QPushButton(self.groupBox)
        self.wip_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        self.wip_pushButton.setObjectName("wip_pushButton")
        self.horizontalLayout_5.addWidget(self.wip_pushButton)
        self.publish_pushButton = QtGui.QPushButton(self.groupBox)
        self.publish_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        self.publish_pushButton.setObjectName("publish_pushButton")
        self.horizontalLayout_5.addWidget(self.publish_pushButton)
        self.gridLayout.addLayout(self.horizontalLayout_5, 7, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setMinimumSize(QtCore.QSize(0, 35))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.task_comboBox = QtGui.QComboBox(self.groupBox)
        self.task_comboBox.setMinimumSize(QtCore.QSize(0, 35))
        self.task_comboBox.setObjectName("task_comboBox")
        self.horizontalLayout_3.addWidget(self.task_comboBox)
        self.gridLayout.addLayout(self.horizontalLayout_3, 3, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setMinimumSize(QtCore.QSize(0, 35))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.project_comboBox = QtGui.QComboBox(self.groupBox)
        self.project_comboBox.setMinimumSize(QtCore.QSize(0, 35))
        self.project_comboBox.setObjectName("project_comboBox")
        self.horizontalLayout.addWidget(self.project_comboBox)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.open_pushButton = QtGui.QPushButton(self.groupBox)
        self.open_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        self.open_pushButton.setObjectName("open_pushButton")
        self.horizontalLayout_4.addWidget(self.open_pushButton)
        self.open_publish_pushButton = QtGui.QPushButton(self.groupBox)
        self.open_publish_pushButton.setMinimumSize(QtCore.QSize(0, 35))
        self.open_publish_pushButton.setObjectName("open_publish_pushButton")
        self.horizontalLayout_4.addWidget(self.open_publish_pushButton)
        self.gridLayout.addLayout(self.horizontalLayout_4, 5, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setMinimumSize(QtCore.QSize(0, 35))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.asset_animation_comboBox = QtGui.QComboBox(self.groupBox)
        self.asset_animation_comboBox.setMinimumSize(QtCore.QSize(0, 35))
        self.asset_animation_comboBox.setObjectName("asset_animation_comboBox")
        self.horizontalLayout_2.addWidget(self.asset_animation_comboBox)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setMinimumSize(QtCore.QSize(0, 35))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.scene_comboBox = QtGui.QComboBox(self.groupBox)
        self.scene_comboBox.setMinimumSize(QtCore.QSize(0, 35))
        self.scene_comboBox.setObjectName("scene_comboBox")
        self.horizontalLayout_6.addWidget(self.scene_comboBox)
        self.gridLayout.addLayout(self.horizontalLayout_6, 2, 0, 1, 1)
        Asset_Manager_MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(Asset_Manager_MainWindow)
        self.statusbar.setObjectName("statusbar")
        Asset_Manager_MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(Asset_Manager_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(Asset_Manager_MainWindow)

    def retranslateUi(self, Asset_Manager_MainWindow):
        Asset_Manager_MainWindow.setWindowTitle(QtGui.QApplication.translate("Asset_Manager_MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Asset_Manager_MainWindow", "Asset Manager", None, QtGui.QApplication.UnicodeUTF8))
        self.save_pushButton.setText(QtGui.QApplication.translate("Asset_Manager_MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.wip_pushButton.setText(QtGui.QApplication.translate("Asset_Manager_MainWindow", "WIP", None, QtGui.QApplication.UnicodeUTF8))
        self.publish_pushButton.setText(QtGui.QApplication.translate("Asset_Manager_MainWindow", "Publish", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Asset_Manager_MainWindow", "Task", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Asset_Manager_MainWindow", "Project", None, QtGui.QApplication.UnicodeUTF8))
        self.open_pushButton.setText(QtGui.QApplication.translate("Asset_Manager_MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.open_publish_pushButton.setText(QtGui.QApplication.translate("Asset_Manager_MainWindow", "Open Publish", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Asset_Manager_MainWindow", "Asset/Animation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Asset_Manager_MainWindow", "Scene", None, QtGui.QApplication.UnicodeUTF8))

