# -*- coding: utf-8 -*-


# Created: Sun Apr 25 04:47:31 2015
#      by: pyside-uic 0.2.14 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(411, 448)
        MainWindow.setMinimumSize(QtCore.QSize(411, 448))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.layout_projectSetings = QtGui.QHBoxLayout()
        self.layout_projectSetings.setObjectName("layout_projectSetings")
        self.groupBox_project = QtGui.QGroupBox(self.dockWidgetContents)
        self.groupBox_project.setFlat(False)
        self.groupBox_project.setObjectName("groupBox_project")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_project)
        self.verticalLayout.setObjectName("verticalLayout")
        self.combo_project = QtGui.QComboBox(self.groupBox_project)
        self.combo_project.setObjectName("combo_project")
        self.combo_project.addItem("")
        self.verticalLayout.addWidget(self.combo_project)
        self.layout_projectSetings.addWidget(self.groupBox_project)
        self.groupBox_openScene = QtGui.QGroupBox(self.dockWidgetContents)
        self.groupBox_openScene.setFlat(False)
        self.groupBox_openScene.setObjectName("groupBox_openScene")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBox_openScene)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.layout_openScene = QtGui.QHBoxLayout()
        self.layout_openScene.setObjectName("layout_openScene")
        self.radio_openScene_wip = QtGui.QRadioButton(self.groupBox_openScene)
        self.radio_openScene_wip.setObjectName("radio_openScene_wip")
        self.layout_openScene.addWidget(self.radio_openScene_wip)
        self.radio_openScene_publish = QtGui.QRadioButton(self.groupBox_openScene)
        self.radio_openScene_publish.setChecked(True)
        self.radio_openScene_publish.setObjectName("radio_openScene_publish")
        self.layout_openScene.addWidget(self.radio_openScene_publish)
        self.horizontalLayout_5.addLayout(self.layout_openScene)
        self.layout_projectSetings.addWidget(self.groupBox_openScene)
        self.groupBox_saveScene = QtGui.QGroupBox(self.dockWidgetContents)
        self.groupBox_saveScene.setFlat(False)
        self.groupBox_saveScene.setObjectName("groupBox_saveScene")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.groupBox_saveScene)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.layout_saveScene = QtGui.QHBoxLayout()
        self.layout_saveScene.setObjectName("layout_saveScene")
        self.radio_saveScene_wip = QtGui.QRadioButton(self.groupBox_saveScene)
        self.radio_saveScene_wip.setObjectName("radio_saveScene_wip")
        self.layout_saveScene.addWidget(self.radio_saveScene_wip)
        self.radio_saveScene_publish = QtGui.QRadioButton(self.groupBox_saveScene)
        self.radio_saveScene_publish.setChecked(True)
        self.radio_saveScene_publish.setObjectName("radio_saveScene_publish")
        self.layout_saveScene.addWidget(self.radio_saveScene_publish)
        self.horizontalLayout_8.addLayout(self.layout_saveScene)
        self.layout_projectSetings.addWidget(self.groupBox_saveScene)
        self.verticalLayout_2.addLayout(self.layout_projectSetings)
        self.groupBox_tasks = QtGui.QGroupBox(self.dockWidgetContents)
        self.groupBox_tasks.setFlat(False)
        self.groupBox_tasks.setObjectName("groupBox_tasks")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_tasks)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_tasks = QtGui.QGridLayout()
        self.gridLayout_tasks.setObjectName("gridLayout_tasks")
        self.checkBox_setupLOD1 = QtGui.QCheckBox(self.groupBox_tasks)
        self.checkBox_setupLOD1.setObjectName("checkBox_setupLOD1")
        self.gridLayout_tasks.addWidget(self.checkBox_setupLOD1, 0, 2, 1, 1)
        self.checkBox_setupLOD0 = QtGui.QCheckBox(self.groupBox_tasks)
        self.checkBox_setupLOD0.setObjectName("checkBox_setupLOD0")
        self.gridLayout_tasks.addWidget(self.checkBox_setupLOD0, 0, 1, 1, 1)
        self.checkBox_modeling = QtGui.QCheckBox(self.groupBox_tasks)
        self.checkBox_modeling.setObjectName("checkBox_modeling")
        self.gridLayout_tasks.addWidget(self.checkBox_modeling, 0, 0, 1, 1)
        self.checkBox_setupLOD2 = QtGui.QCheckBox(self.groupBox_tasks)
        self.checkBox_setupLOD2.setObjectName("checkBox_setupLOD2")
        self.gridLayout_tasks.addWidget(self.checkBox_setupLOD2, 1, 0, 1, 1)
        self.checkBox_assemblyDef = QtGui.QCheckBox(self.groupBox_tasks)
        self.checkBox_assemblyDef.setObjectName("checkBox_assemblyDef")
        self.gridLayout_tasks.addWidget(self.checkBox_assemblyDef, 1, 1, 1, 1)
        self.checkBox_set = QtGui.QCheckBox(self.groupBox_tasks)
        self.checkBox_set.setObjectName("checkBox_set")
        self.gridLayout_tasks.addWidget(self.checkBox_set, 1, 2, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_tasks)
        self.verticalLayout_2.addWidget(self.groupBox_tasks)
        self.groupBox_assets = QtGui.QGroupBox(self.dockWidgetContents)
        self.groupBox_assets.setFlat(False)
        self.groupBox_assets.setObjectName("groupBox_assets")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_assets)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.textedit_asset_list = QtGui.QPlainTextEdit(self.groupBox_assets)
        self.textedit_asset_list.setObjectName("textedit_asset_list")
        self.verticalLayout_5.addWidget(self.textedit_asset_list)
        self.verticalLayout_2.addWidget(self.groupBox_assets)
        self.groupBox_cmds = QtGui.QGroupBox(self.dockWidgetContents)
        self.groupBox_cmds.setFlat(False)
        self.groupBox_cmds.setObjectName("groupBox_cmds")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_cmds)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.textEdit_cmds = QtGui.QPlainTextEdit(self.groupBox_cmds)
        self.textEdit_cmds.setObjectName("textEdit_cmds")
        self.verticalLayout_4.addWidget(self.textEdit_cmds)
        self.verticalLayout_2.addWidget(self.groupBox_cmds)
        self.layout_end_button = QtGui.QHBoxLayout()
        self.layout_end_button.setObjectName("layout_end_button")
        self.button_dataCheck = QtGui.QPushButton(self.dockWidgetContents)
        self.button_dataCheck.setObjectName("button_dataCheck")
        self.layout_end_button.addWidget(self.button_dataCheck)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.layout_end_button.addItem(spacerItem)
        self.button_batch = QtGui.QPushButton(self.dockWidgetContents)
        self.button_batch.setObjectName("button_batch")
        self.layout_end_button.addWidget(self.button_batch)
        self.verticalLayout_2.addLayout(self.layout_end_button)
        MainWindow.setWidget(self.dockWidgetContents)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "DockWidget", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_project.setTitle(QtGui.QApplication.translate("MainWindow", "Project :", None, QtGui.QApplication.UnicodeUTF8))
        self.combo_project.setItemText(0, QtGui.QApplication.translate("MainWindow", "413_StellaSerie", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_openScene.setTitle(QtGui.QApplication.translate("MainWindow", "Open scene from:", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_openScene_wip.setText(QtGui.QApplication.translate("MainWindow", "wip", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_openScene_publish.setText(QtGui.QApplication.translate("MainWindow", "publish", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_saveScene.setTitle(QtGui.QApplication.translate("MainWindow", "Save scene to :", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_saveScene_wip.setText(QtGui.QApplication.translate("MainWindow", "wip", None, QtGui.QApplication.UnicodeUTF8))
        self.radio_saveScene_publish.setText(QtGui.QApplication.translate("MainWindow", "publish", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_tasks.setTitle(QtGui.QApplication.translate("MainWindow", "Tasks :", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_setupLOD1.setText(QtGui.QApplication.translate("MainWindow", "setupLOD1", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_setupLOD0.setText(QtGui.QApplication.translate("MainWindow", "setupLOD0", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_modeling.setText(QtGui.QApplication.translate("MainWindow", "modeling", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_setupLOD2.setText(QtGui.QApplication.translate("MainWindow", "setupLOD2", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_assemblyDef.setText(QtGui.QApplication.translate("MainWindow", "assemblyDef", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_set.setText(QtGui.QApplication.translate("MainWindow", "set", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_assets.setTitle(QtGui.QApplication.translate("MainWindow", "Assets to batch :", None, QtGui.QApplication.UnicodeUTF8))
        self.textedit_asset_list.setPlainText(QtGui.QApplication.translate("MainWindow", "[\'cube001\', \'cube002\']", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_cmds.setTitle(QtGui.QApplication.translate("MainWindow", "Commands to batch :", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_cmds.setPlainText(QtGui.QApplication.translate("MainWindow", "[\'mc.doSommeThings()\',\'cmds.makeMeHappy()\',\'cube.beGood(*args)\']", None, QtGui.QApplication.UnicodeUTF8))
        self.button_dataCheck.setText(QtGui.QApplication.translate("MainWindow", "Check Datas", None, QtGui.QApplication.UnicodeUTF8))
        self.button_batch.setText(QtGui.QApplication.translate("MainWindow", "                              Batch                              ", None, QtGui.QApplication.UnicodeUTF8))

